/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['input.ng-dirty.ng-invalid[_ngcontent-%COMP%] { border: 2px solid #ff0000 }\r\ninput.ng-dirty.ng-valid[_ngcontent-%COMP%] { border: 2px solid #6bc502 }'];