/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from '../../../app/store/store.module';
import * as import2 from '@angular/http/src/http_module';
import * as import3 from '../../../app/model/model.module';
import * as import4 from '@angular/common/src/common_module';
import * as import5 from '@angular/core/src/application_module';
import * as import6 from '@angular/platform-browser/src/browser';
import * as import7 from '@angular/forms/src/directives';
import * as import8 from '@angular/forms/src/form_providers';
import * as import9 from '@angular/router/src/router_module';
import * as import10 from '@angular/http/src/backends/browser_xhr';
import * as import11 from '@angular/http/src/base_response_options';
import * as import12 from '@angular/http/src/backends/xhr_backend';
import * as import13 from '@angular/http/src/base_request_options';
import * as import14 from '../../../app/model/rest.datasource';
import * as import15 from '../../../app/model/product.repository';
import * as import16 from '../../../app/model/cart.model';
import * as import17 from '../../../app/model/order.model';
import * as import18 from '../../../app/model/order.repository';
import * as import19 from '../../../app/model/auth.service';
import * as import20 from '@angular/common/src/localization';
import * as import21 from '@angular/core/src/application_init';
import * as import22 from '@angular/core/src/testability/testability';
import * as import23 from '@angular/core/src/application_ref';
import * as import24 from '@angular/core/src/linker/compiler';
import * as import25 from '@angular/platform-browser/src/dom/events/hammer_gestures';
import * as import26 from '@angular/platform-browser/src/dom/events/event_manager';
import * as import27 from '@angular/platform-browser/src/dom/shared_styles_host';
import * as import28 from '@angular/platform-browser/src/dom/dom_renderer';
import * as import29 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import30 from '@angular/core/src/linker/view_utils';
import * as import31 from '@angular/platform-browser/src/browser/title';
import * as import32 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import33 from '@angular/core/src/di/injector';
import * as import34 from '@angular/core/src/application_tokens';
import * as import35 from '@angular/platform-browser/src/dom/events/dom_events';
import * as import36 from '@angular/platform-browser/src/dom/events/key_events';
import * as import37 from '@angular/core/src/zone/ng_zone';
import * as import38 from '@angular/platform-browser/src/dom/debug/ng_probe';
import * as import39 from '@angular/core/src/console';
import * as import40 from '@angular/http/src/interfaces';
import * as import41 from '@angular/http/src/http';
import * as import42 from '../../../app/model/static.datasource';
import * as import43 from '@angular/core/src/i18n/tokens';
import * as import44 from '@angular/core/src/error_handler';
import * as import45 from '@angular/platform-browser/src/dom/dom_tokens';
import * as import46 from '@angular/platform-browser/src/dom/animation_driver';
import * as import47 from '@angular/core/src/render/api';
import * as import48 from '@angular/core/src/security';
import * as import49 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import50 from '@angular/core/src/change_detection/differs/keyvalue_differs';
class StoreModuleInjector extends import0.NgModuleInjector<import1.StoreModule> {
  _HttpModule_0:import2.HttpModule;
  _ModelModule_1:import3.ModelModule;
  _CommonModule_2:import4.CommonModule;
  _ApplicationModule_3:import5.ApplicationModule;
  _BrowserModule_4:import6.BrowserModule;
  _InternalFormsSharedModule_5:import7.InternalFormsSharedModule;
  _FormsModule_6:import8.FormsModule;
  _RouterModule_7:import9.RouterModule;
  _StoreModule_8:import1.StoreModule;
  __BrowserXhr_9:import10.BrowserXhr;
  __ResponseOptions_10:import11.BaseResponseOptions;
  __XSRFStrategy_11:any;
  __XHRBackend_12:import12.XHRBackend;
  __RequestOptions_13:import13.BaseRequestOptions;
  __Http_14:any;
  __RestDataSource_15:import14.RestDataSource;
  __ProductRepository_16:import15.ProductRepository;
  __Cart_17:import16.Cart;
  __Order_18:import17.Order;
  __OrderRepository_19:import18.OrderRepository;
  __StaticDataSource_20:import14.RestDataSource;
  __AuthService_21:import19.AuthService;
  __LOCALE_ID_22:any;
  __NgLocalization_23:import20.NgLocaleLocalization;
  _ErrorHandler_24:any;
  _ApplicationInitStatus_25:import21.ApplicationInitStatus;
  _Testability_26:import22.Testability;
  _ApplicationRef__27:import23.ApplicationRef_;
  __ApplicationRef_28:any;
  __Compiler_29:import24.Compiler;
  __APP_ID_30:any;
  __DOCUMENT_31:any;
  __HAMMER_GESTURE_CONFIG_32:import25.HammerGestureConfig;
  __EVENT_MANAGER_PLUGINS_33:any[];
  __EventManager_34:import26.EventManager;
  __DomSharedStylesHost_35:import27.DomSharedStylesHost;
  __AnimationDriver_36:any;
  __DomRootRenderer_37:import28.DomRootRenderer_;
  __RootRenderer_38:any;
  __DomSanitizer_39:import29.DomSanitizerImpl;
  __Sanitizer_40:any;
  __ViewUtils_41:import30.ViewUtils;
  __IterableDiffers_42:any;
  __KeyValueDiffers_43:any;
  __SharedStylesHost_44:any;
  __Title_45:import31.Title;
  __RadioControlRegistry_46:import32.RadioControlRegistry;
  constructor(parent:import33.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  get _BrowserXhr_9():import10.BrowserXhr {
    if ((this.__BrowserXhr_9 == null)) { (this.__BrowserXhr_9 = new import10.BrowserXhr()); }
    return this.__BrowserXhr_9;
  }
  get _ResponseOptions_10():import11.BaseResponseOptions {
    if ((this.__ResponseOptions_10 == null)) { (this.__ResponseOptions_10 = new import11.BaseResponseOptions()); }
    return this.__ResponseOptions_10;
  }
  get _XSRFStrategy_11():any {
    if ((this.__XSRFStrategy_11 == null)) { (this.__XSRFStrategy_11 = import2._createDefaultCookieXSRFStrategy()); }
    return this.__XSRFStrategy_11;
  }
  get _XHRBackend_12():import12.XHRBackend {
    if ((this.__XHRBackend_12 == null)) { (this.__XHRBackend_12 = new import12.XHRBackend(this._BrowserXhr_9,this._ResponseOptions_10,this._XSRFStrategy_11)); }
    return this.__XHRBackend_12;
  }
  get _RequestOptions_13():import13.BaseRequestOptions {
    if ((this.__RequestOptions_13 == null)) { (this.__RequestOptions_13 = new import13.BaseRequestOptions()); }
    return this.__RequestOptions_13;
  }
  get _Http_14():any {
    if ((this.__Http_14 == null)) { (this.__Http_14 = import2.httpFactory(this._XHRBackend_12,this._RequestOptions_13)); }
    return this.__Http_14;
  }
  get _RestDataSource_15():import14.RestDataSource {
    if ((this.__RestDataSource_15 == null)) { (this.__RestDataSource_15 = new import14.RestDataSource(this._Http_14)); }
    return this.__RestDataSource_15;
  }
  get _ProductRepository_16():import15.ProductRepository {
    if ((this.__ProductRepository_16 == null)) { (this.__ProductRepository_16 = new import15.ProductRepository(this._RestDataSource_15)); }
    return this.__ProductRepository_16;
  }
  get _Cart_17():import16.Cart {
    if ((this.__Cart_17 == null)) { (this.__Cart_17 = new import16.Cart()); }
    return this.__Cart_17;
  }
  get _Order_18():import17.Order {
    if ((this.__Order_18 == null)) { (this.__Order_18 = new import17.Order(this._Cart_17)); }
    return this.__Order_18;
  }
  get _OrderRepository_19():import18.OrderRepository {
    if ((this.__OrderRepository_19 == null)) { (this.__OrderRepository_19 = new import18.OrderRepository(this._RestDataSource_15)); }
    return this.__OrderRepository_19;
  }
  get _StaticDataSource_20():import14.RestDataSource {
    if ((this.__StaticDataSource_20 == null)) { (this.__StaticDataSource_20 = new import14.RestDataSource(this._Http_14)); }
    return this.__StaticDataSource_20;
  }
  get _AuthService_21():import19.AuthService {
    if ((this.__AuthService_21 == null)) { (this.__AuthService_21 = new import19.AuthService(this._RestDataSource_15)); }
    return this.__AuthService_21;
  }
  get _LOCALE_ID_22():any {
    if ((this.__LOCALE_ID_22 == null)) { (this.__LOCALE_ID_22 = 'en-US'); }
    return this.__LOCALE_ID_22;
  }
  get _NgLocalization_23():import20.NgLocaleLocalization {
    if ((this.__NgLocalization_23 == null)) { (this.__NgLocalization_23 = new import20.NgLocaleLocalization(this._LOCALE_ID_22)); }
    return this.__NgLocalization_23;
  }
  get _ApplicationRef_28():any {
    if ((this.__ApplicationRef_28 == null)) { (this.__ApplicationRef_28 = this._ApplicationRef__27); }
    return this.__ApplicationRef_28;
  }
  get _Compiler_29():import24.Compiler {
    if ((this.__Compiler_29 == null)) { (this.__Compiler_29 = new import24.Compiler()); }
    return this.__Compiler_29;
  }
  get _APP_ID_30():any {
    if ((this.__APP_ID_30 == null)) { (this.__APP_ID_30 = import34._appIdRandomProviderFactory()); }
    return this.__APP_ID_30;
  }
  get _DOCUMENT_31():any {
    if ((this.__DOCUMENT_31 == null)) { (this.__DOCUMENT_31 = import6._document()); }
    return this.__DOCUMENT_31;
  }
  get _HAMMER_GESTURE_CONFIG_32():import25.HammerGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_32 == null)) { (this.__HAMMER_GESTURE_CONFIG_32 = new import25.HammerGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_32;
  }
  get _EVENT_MANAGER_PLUGINS_33():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_33 == null)) { (this.__EVENT_MANAGER_PLUGINS_33 = [
      new import35.DomEventsPlugin(),
      new import36.KeyEventsPlugin(),
      new import25.HammerGesturesPlugin(this._HAMMER_GESTURE_CONFIG_32)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_33;
  }
  get _EventManager_34():import26.EventManager {
    if ((this.__EventManager_34 == null)) { (this.__EventManager_34 = new import26.EventManager(this._EVENT_MANAGER_PLUGINS_33,this.parent.get(import37.NgZone))); }
    return this.__EventManager_34;
  }
  get _DomSharedStylesHost_35():import27.DomSharedStylesHost {
    if ((this.__DomSharedStylesHost_35 == null)) { (this.__DomSharedStylesHost_35 = new import27.DomSharedStylesHost(this._DOCUMENT_31)); }
    return this.__DomSharedStylesHost_35;
  }
  get _AnimationDriver_36():any {
    if ((this.__AnimationDriver_36 == null)) { (this.__AnimationDriver_36 = import6._resolveDefaultAnimationDriver()); }
    return this.__AnimationDriver_36;
  }
  get _DomRootRenderer_37():import28.DomRootRenderer_ {
    if ((this.__DomRootRenderer_37 == null)) { (this.__DomRootRenderer_37 = new import28.DomRootRenderer_(this._DOCUMENT_31,this._EventManager_34,this._DomSharedStylesHost_35,this._AnimationDriver_36,this._APP_ID_30)); }
    return this.__DomRootRenderer_37;
  }
  get _RootRenderer_38():any {
    if ((this.__RootRenderer_38 == null)) { (this.__RootRenderer_38 = import38._createConditionalRootRenderer(this._DomRootRenderer_37,this.parent.get(import38.NgProbeToken,(null as any)))); }
    return this.__RootRenderer_38;
  }
  get _DomSanitizer_39():import29.DomSanitizerImpl {
    if ((this.__DomSanitizer_39 == null)) { (this.__DomSanitizer_39 = new import29.DomSanitizerImpl()); }
    return this.__DomSanitizer_39;
  }
  get _Sanitizer_40():any {
    if ((this.__Sanitizer_40 == null)) { (this.__Sanitizer_40 = this._DomSanitizer_39); }
    return this.__Sanitizer_40;
  }
  get _ViewUtils_41():import30.ViewUtils {
    if ((this.__ViewUtils_41 == null)) { (this.__ViewUtils_41 = new import30.ViewUtils(this._RootRenderer_38,this._Sanitizer_40)); }
    return this.__ViewUtils_41;
  }
  get _IterableDiffers_42():any {
    if ((this.__IterableDiffers_42 == null)) { (this.__IterableDiffers_42 = import5._iterableDiffersFactory()); }
    return this.__IterableDiffers_42;
  }
  get _KeyValueDiffers_43():any {
    if ((this.__KeyValueDiffers_43 == null)) { (this.__KeyValueDiffers_43 = import5._keyValueDiffersFactory()); }
    return this.__KeyValueDiffers_43;
  }
  get _SharedStylesHost_44():any {
    if ((this.__SharedStylesHost_44 == null)) { (this.__SharedStylesHost_44 = this._DomSharedStylesHost_35); }
    return this.__SharedStylesHost_44;
  }
  get _Title_45():import31.Title {
    if ((this.__Title_45 == null)) { (this.__Title_45 = new import31.Title()); }
    return this.__Title_45;
  }
  get _RadioControlRegistry_46():import32.RadioControlRegistry {
    if ((this.__RadioControlRegistry_46 == null)) { (this.__RadioControlRegistry_46 = new import32.RadioControlRegistry()); }
    return this.__RadioControlRegistry_46;
  }
  createInternal():import1.StoreModule {
    this._HttpModule_0 = new import2.HttpModule();
    this._ModelModule_1 = new import3.ModelModule();
    this._CommonModule_2 = new import4.CommonModule();
    this._ApplicationModule_3 = new import5.ApplicationModule();
    this._BrowserModule_4 = new import6.BrowserModule(this.parent.get(import6.BrowserModule,(null as any)));
    this._InternalFormsSharedModule_5 = new import7.InternalFormsSharedModule();
    this._FormsModule_6 = new import8.FormsModule();
    this._RouterModule_7 = new import9.RouterModule(this.parent.get(import9.ROUTER_FORROOT_GUARD,(null as any)));
    this._StoreModule_8 = new import1.StoreModule();
    this._ErrorHandler_24 = import6.errorHandler();
    this._ApplicationInitStatus_25 = new import21.ApplicationInitStatus(this.parent.get(import21.APP_INITIALIZER,(null as any)));
    this._Testability_26 = new import22.Testability(this.parent.get(import37.NgZone));
    this._ApplicationRef__27 = new import23.ApplicationRef_(this.parent.get(import37.NgZone),this.parent.get(import39.Console),this,this._ErrorHandler_24,this,this._ApplicationInitStatus_25,this.parent.get(import22.TestabilityRegistry,(null as any)),this._Testability_26);
    return this._StoreModule_8;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.HttpModule)) { return this._HttpModule_0; }
    if ((token === import3.ModelModule)) { return this._ModelModule_1; }
    if ((token === import4.CommonModule)) { return this._CommonModule_2; }
    if ((token === import5.ApplicationModule)) { return this._ApplicationModule_3; }
    if ((token === import6.BrowserModule)) { return this._BrowserModule_4; }
    if ((token === import7.InternalFormsSharedModule)) { return this._InternalFormsSharedModule_5; }
    if ((token === import8.FormsModule)) { return this._FormsModule_6; }
    if ((token === import9.RouterModule)) { return this._RouterModule_7; }
    if ((token === import1.StoreModule)) { return this._StoreModule_8; }
    if ((token === import10.BrowserXhr)) { return this._BrowserXhr_9; }
    if ((token === import11.ResponseOptions)) { return this._ResponseOptions_10; }
    if ((token === import40.XSRFStrategy)) { return this._XSRFStrategy_11; }
    if ((token === import12.XHRBackend)) { return this._XHRBackend_12; }
    if ((token === import13.RequestOptions)) { return this._RequestOptions_13; }
    if ((token === import41.Http)) { return this._Http_14; }
    if ((token === import14.RestDataSource)) { return this._RestDataSource_15; }
    if ((token === import15.ProductRepository)) { return this._ProductRepository_16; }
    if ((token === import16.Cart)) { return this._Cart_17; }
    if ((token === import17.Order)) { return this._Order_18; }
    if ((token === import18.OrderRepository)) { return this._OrderRepository_19; }
    if ((token === import42.StaticDataSource)) { return this._StaticDataSource_20; }
    if ((token === import19.AuthService)) { return this._AuthService_21; }
    if ((token === import43.LOCALE_ID)) { return this._LOCALE_ID_22; }
    if ((token === import20.NgLocalization)) { return this._NgLocalization_23; }
    if ((token === import44.ErrorHandler)) { return this._ErrorHandler_24; }
    if ((token === import21.ApplicationInitStatus)) { return this._ApplicationInitStatus_25; }
    if ((token === import22.Testability)) { return this._Testability_26; }
    if ((token === import23.ApplicationRef_)) { return this._ApplicationRef__27; }
    if ((token === import23.ApplicationRef)) { return this._ApplicationRef_28; }
    if ((token === import24.Compiler)) { return this._Compiler_29; }
    if ((token === import34.APP_ID)) { return this._APP_ID_30; }
    if ((token === import45.DOCUMENT)) { return this._DOCUMENT_31; }
    if ((token === import25.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_32; }
    if ((token === import26.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_33; }
    if ((token === import26.EventManager)) { return this._EventManager_34; }
    if ((token === import27.DomSharedStylesHost)) { return this._DomSharedStylesHost_35; }
    if ((token === import46.AnimationDriver)) { return this._AnimationDriver_36; }
    if ((token === import28.DomRootRenderer)) { return this._DomRootRenderer_37; }
    if ((token === import47.RootRenderer)) { return this._RootRenderer_38; }
    if ((token === import29.DomSanitizer)) { return this._DomSanitizer_39; }
    if ((token === import48.Sanitizer)) { return this._Sanitizer_40; }
    if ((token === import30.ViewUtils)) { return this._ViewUtils_41; }
    if ((token === import49.IterableDiffers)) { return this._IterableDiffers_42; }
    if ((token === import50.KeyValueDiffers)) { return this._KeyValueDiffers_43; }
    if ((token === import27.SharedStylesHost)) { return this._SharedStylesHost_44; }
    if ((token === import31.Title)) { return this._Title_45; }
    if ((token === import32.RadioControlRegistry)) { return this._RadioControlRegistry_46; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ApplicationRef__27.ngOnDestroy();
  }
}
export const StoreModuleNgFactory:import0.NgModuleFactory<import1.StoreModule> = new import0.NgModuleFactory(StoreModuleInjector,import1.StoreModule);