/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../app/admin/admin.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/change_detection';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '../../../app/model/auth.service';
import * as import9 from '@angular/router/src/router';
import * as import10 from '../../node_modules/@angular/router/src/directives/router_link.ngfactory';
import * as import11 from '../../node_modules/@angular/router/src/directives/router_link_active.ngfactory';
import * as import12 from '@angular/core/src/linker/query_list';
import * as import13 from '@angular/core/src/linker/view_container';
import * as import14 from '../../node_modules/@angular/router/src/directives/router_outlet.ngfactory';
import * as import15 from '@angular/router/src/router_state';
import * as import16 from '@angular/common/src/location/location_strategy';
import * as import17 from '@angular/core/src/linker/element_ref';
import * as import18 from '@angular/router/src/router_outlet_map';
import * as import19 from '@angular/core/src/linker/component_factory_resolver';
import * as import20 from '@angular/router/src/directives/router_link';
import * as import21 from '@angular/router/src/directives/router_link_active';
import * as import22 from '@angular/router/src/directives/router_outlet';
export class Wrapper_AdminComponent {
  /*private*/ _eventHandler:Function;
  context:import0.AdminComponent;
  /*private*/ _changed:boolean;
  constructor(p0:any,p1:any) {
    this._changed = false;
    this.context = new import0.AdminComponent(p0,p1);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_AdminComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_AdminComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.AdminComponent>;
  _AdminComponent_0_3:Wrapper_AdminComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_AdminComponent_Host0,renderType_AdminComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'ng-component',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_AdminComponent0(this.viewUtils,this,0,this._el_0);
    this._AdminComponent_0_3 = new Wrapper_AdminComponent(this.injectorGet(import8.AuthService,this.parentIndex),this.injectorGet(import9.Router,this.parentIndex));
    this.compView_0.create(this._AdminComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._AdminComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.AdminComponent) && (0 === requestNodeIndex))) { return this._AdminComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._AdminComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const AdminComponentNgFactory:import7.ComponentFactory<import0.AdminComponent> = new import7.ComponentFactory<import0.AdminComponent>('ng-component',View_AdminComponent_Host0,import0.AdminComponent);
const styles_AdminComponent:any[] = ([] as any[]);
var renderType_AdminComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,styles_AdminComponent,{});
export class View_AdminComponent0 extends import1.AppView<import0.AdminComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _el_10:any;
  _RouterLink_10_3:import10.Wrapper_RouterLink;
  _RouterLinkActive_10_4:import11.Wrapper_RouterLinkActive;
  _query_RouterLink_10_0:import12.QueryList<any>;
  _query_RouterLinkWithHref_10_1:import12.QueryList<any>;
  _text_11:any;
  _text_12:any;
  _el_13:any;
  _RouterLink_13_3:import10.Wrapper_RouterLink;
  _RouterLinkActive_13_4:import11.Wrapper_RouterLinkActive;
  _query_RouterLink_13_0:import12.QueryList<any>;
  _query_RouterLinkWithHref_13_1:import12.QueryList<any>;
  _text_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _text_18:any;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _el_22:any;
  /*private*/ _vc_22:import13.ViewContainer;
  _RouterOutlet_22_5:import14.Wrapper_RouterOutlet;
  _text_23:any;
  _text_24:any;
  _text_25:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_AdminComponent0,renderType_AdminComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','navbar navbar-inverse bg-info'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'  \n    ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'a',new import3.InlineArray2(2,'class','navbar-brand'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'SPORTS STORE Admin',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'  \n',(null as any));
    this._text_5 = this.renderer.createText(parentRenderNode,'  \n',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','m-t-1'),(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'\n    ',(null as any));
    this._el_8 = import3.createRenderElement(this.renderer,this._el_6,'div',new import3.InlineArray2(2,'class','col-xs-3'),(null as any));
    this._text_9 = this.renderer.createText(this._el_8,'\n        ',(null as any));
    this._el_10 = import3.createRenderElement(this.renderer,this._el_8,'button',new import3.InlineArray8(6,'class','btn btn-outline-info btn-block','routerLink','/admin/main/products','routerLinkActive','active'),(null as any));
    this._RouterLink_10_3 = new import10.Wrapper_RouterLink(this.parentView.injectorGet(import9.Router,this.parentIndex),this.parentView.injectorGet(import15.ActivatedRoute,this.parentIndex),this.parentView.injectorGet(import16.LocationStrategy,this.parentIndex));
    this._RouterLinkActive_10_4 = new import11.Wrapper_RouterLinkActive(this.parentView.injectorGet(import9.Router,this.parentIndex),new import17.ElementRef(this._el_10),this.renderer);
    this._query_RouterLink_10_0 = new import12.QueryList<any>();
    this._query_RouterLinkWithHref_10_1 = new import12.QueryList<any>();
    this._text_11 = this.renderer.createText(this._el_10,'\n            Products\n        ',(null as any));
    this._text_12 = this.renderer.createText(this._el_8,'\n        ',(null as any));
    this._el_13 = import3.createRenderElement(this.renderer,this._el_8,'button',new import3.InlineArray8(6,'class','btn btn-outline-info btn-block','routerLink','/admin/main/orders','routerLinkActive','active'),(null as any));
    this._RouterLink_13_3 = new import10.Wrapper_RouterLink(this.parentView.injectorGet(import9.Router,this.parentIndex),this.parentView.injectorGet(import15.ActivatedRoute,this.parentIndex),this.parentView.injectorGet(import16.LocationStrategy,this.parentIndex));
    this._RouterLinkActive_13_4 = new import11.Wrapper_RouterLinkActive(this.parentView.injectorGet(import9.Router,this.parentIndex),new import17.ElementRef(this._el_13),this.renderer);
    this._query_RouterLink_13_0 = new import12.QueryList<any>();
    this._query_RouterLinkWithHref_13_1 = new import12.QueryList<any>();
    this._text_14 = this.renderer.createText(this._el_13,'\n            Orders\n        ',(null as any));
    this._text_15 = this.renderer.createText(this._el_8,'\n        ',(null as any));
    this._el_16 = import3.createRenderElement(this.renderer,this._el_8,'button',new import3.InlineArray2(2,'class','btn btn-outline-danger btn-block'),(null as any));
    this._text_17 = this.renderer.createText(this._el_16,'\n            Logout\n        ',(null as any));
    this._text_18 = this.renderer.createText(this._el_8,'\n    ',(null as any));
    this._text_19 = this.renderer.createText(this._el_6,'\n    ',(null as any));
    this._el_20 = import3.createRenderElement(this.renderer,this._el_6,'div',new import3.InlineArray2(2,'class','col-xs-9'),(null as any));
    this._text_21 = this.renderer.createText(this._el_20,'\n        ',(null as any));
    this._el_22 = import3.createRenderElement(this.renderer,this._el_20,'router-outlet',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._vc_22 = new import13.ViewContainer(22,20,this,this._el_22);
    this._RouterOutlet_22_5 = new import14.Wrapper_RouterOutlet(this.parentView.injectorGet(import18.RouterOutletMap,this.parentIndex),this._vc_22.vcRef,this.parentView.injectorGet(import19.ComponentFactoryResolver,this.parentIndex),(null as any));
    this._text_23 = this.renderer.createText(this._el_20,'\n    ',(null as any));
    this._text_24 = this.renderer.createText(this._el_6,'\n',(null as any));
    this._text_25 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_10,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_10));
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_13,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_13));
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_16,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_16));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._text_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._text_24,
      this._text_25
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import20.RouterLink) && ((10 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._RouterLink_10_3.context; }
    if (((token === import21.RouterLinkActive) && ((10 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._RouterLinkActive_10_4.context; }
    if (((token === import20.RouterLink) && ((13 <= requestNodeIndex) && (requestNodeIndex <= 14)))) { return this._RouterLink_13_3.context; }
    if (((token === import21.RouterLinkActive) && ((13 <= requestNodeIndex) && (requestNodeIndex <= 14)))) { return this._RouterLinkActive_13_4.context; }
    if (((token === import22.RouterOutlet) && (22 === requestNodeIndex))) { return this._RouterOutlet_22_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_10_0_0:any = '/admin/main/products';
    this._RouterLink_10_3.check_routerLink(currVal_10_0_0,throwOnChange,false);
    this._RouterLink_10_3.ngDoCheck(this,this._el_10,throwOnChange);
    const currVal_10_1_0:any = 'active';
    this._RouterLinkActive_10_4.check_routerLinkActive(currVal_10_1_0,throwOnChange,false);
    this._RouterLinkActive_10_4.ngDoCheck(this,this._el_10,throwOnChange);
    const currVal_13_0_0:any = '/admin/main/orders';
    this._RouterLink_13_3.check_routerLink(currVal_13_0_0,throwOnChange,false);
    this._RouterLink_13_3.ngDoCheck(this,this._el_13,throwOnChange);
    const currVal_13_1_0:any = 'active';
    this._RouterLinkActive_13_4.check_routerLinkActive(currVal_13_1_0,throwOnChange,false);
    this._RouterLinkActive_13_4.ngDoCheck(this,this._el_13,throwOnChange);
    this._RouterOutlet_22_5.ngDoCheck(this,this._el_22,throwOnChange);
    this._vc_22.detectChangesInNestedViews(throwOnChange);
    if (!throwOnChange) {
      if (this._query_RouterLink_10_0.dirty) {
        this._query_RouterLink_10_0.reset([this._RouterLink_10_3.context]);
        this._RouterLinkActive_10_4.context.links = this._query_RouterLink_10_0;
        this._query_RouterLink_10_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_10_1.dirty) {
        this._query_RouterLinkWithHref_10_1.reset(([] as any[]));
        this._RouterLinkActive_10_4.context.linksWithHrefs = this._query_RouterLinkWithHref_10_1;
        this._query_RouterLinkWithHref_10_1.notifyOnChanges();
      }
      if (this._query_RouterLink_13_0.dirty) {
        this._query_RouterLink_13_0.reset([this._RouterLink_13_3.context]);
        this._RouterLinkActive_13_4.context.links = this._query_RouterLink_13_0;
        this._query_RouterLink_13_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_13_1.dirty) {
        this._query_RouterLinkWithHref_13_1.reset(([] as any[]));
        this._RouterLinkActive_13_4.context.linksWithHrefs = this._query_RouterLinkWithHref_13_1;
        this._query_RouterLinkWithHref_13_1.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_10_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_13_4.context.ngAfterContentInit(); }
    }
  }
  destroyInternal():void {
    this._vc_22.destroyNestedViews();
    this._RouterLinkActive_10_4.ngOnDestroy();
    this._RouterLinkActive_13_4.ngOnDestroy();
    this._RouterOutlet_22_5.ngOnDestroy();
  }
  handleEvent_10(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLink_10_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_13(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLink_13_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_16(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.logout()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}